package view;

import model.room.Room;

import javax.swing.*;
import java.awt.*;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.IOException;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;

import static controller.PropertyChangeEnabledUserControls.*;


/**
 * Main GUI class. Contains all panels and GUI elements displayed to the screen.
 * @author Dustin Ray
 * @version Summer 2021
 */
public class OfficeEscapeView extends JFrame implements PropertyChangeListener {

    /** The current room panel which renders the game room to the screen. */
    RoomPanel myCurrentRoomPanel;
    /** The current toolbar menu which contains options for loading, saving, etc. */
    ToolbarMenu myCurrentToolbarMenu;
    /** The main menu panel of the game which is shown on game load. */
    MainMenuPanel myMainMenuPanel;
    /** The panel that shows text output from the NPCs. */
    ConsolePanel myConsolePanel;
    /** A list of rooms generated by room manager. */
    List<Room> myRoomList;
    /** The mappings of all rooms to their connected rooms. */
    HashMap<Room, HashSet<Room>> myRoomsMap;

    /**
     * Constructor for class. Sets up all panels in the order in which they should appear.
     * @param theRoomsList the list of rooms generated by room manager.
     * @param theRoomsMap the mappings of all rooms to their connected rooms.
     * @throws ClassNotFoundException if cannot load system l/f.
     * @throws InstantiationException if cannot load system l/f.
     * @throws IllegalAccessException if cannot load system l/f.
     * @throws UnsupportedLookAndFeelException if cannot load system l/f.
     * @throws IOException if cannot load system l/f.
     * @throws FontFormatException if cannot load a given font file.
     */
    public OfficeEscapeView(List<Room> theRoomsList,
                            HashMap<Room, HashSet<Room>> theRoomsMap) throws
            ClassNotFoundException,
            InstantiationException,
            IllegalAccessException,
            UnsupportedLookAndFeelException,
            IOException,
            FontFormatException {

        super("Office Escape 9: The Story Continues");
//        this.setLayout(null);
        myRoomsMap = theRoomsMap;
        myRoomList = theRoomsList;
        myCurrentToolbarMenu = new ToolbarMenu();
        myMainMenuPanel = new MainMenuPanel();
        myConsolePanel = new ConsolePanel();
        setupUI();
        setupFrame();
        addToolbarPanel();
        setupRoomPanel();
        addConsolePanel();
        this.setVisible(true);
        this.setResizable(false);
    }

    /** Initializes the current frame to hold all of the panels. Dimensions are set in
     * multiples of 96 which is the default grid square size. */
    private void setupFrame() {

        this.setSize(1248, 828);
        this.setLocation(500, 100);
        this.setBackground(Color.BLACK);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }


    /** Adds a console panel to the frame. */
    private void addConsolePanel() {
        myConsolePanel.setFocusable(true);
        myConsolePanel.setBounds(768, 0, 480, 480);
        this.getContentPane().add(myConsolePanel);
        myConsolePanel.setVisible(true);
        myConsolePanel.repaint();

    }


    /** Adds a main menu panel to the frame. */
    private void addMainMenuPanel() {
        myMainMenuPanel.setFocusable(true);
        this.add(myMainMenuPanel);
        myMainMenuPanel.repaint();
        myMainMenuPanel.setBounds(0, 0, 1248, 768);
    }

    /** Adds a toolbar menu to the top of the frame which contains options
     * for loading, saving, returning to main menu, etc. */
    private void addToolbarPanel() {
        this.setJMenuBar(myCurrentToolbarMenu.menubar);
        myCurrentToolbarMenu.setVisible(true);
        myConsolePanel.setVisible(false);
    }

    /**
     * Initializes the current room panel. Probably contains redundant code.
     * @throws IOException if any resources cannot be loaded.
     */
    private void setupRoomPanel() throws IOException {
        myCurrentRoomPanel = new RoomPanel(myRoomList.get(0));
        myCurrentRoomPanel.setBounds(-96, 0, 864, 768);
        myCurrentRoomPanel.userControls.addPropertyChangeListener(myConsolePanel);
        myCurrentRoomPanel.userControls.addPropertyChangeListener(this);
//        this.remove(myMainMenuPanel);
        this.add(myCurrentRoomPanel);
//        this.setBackground(Color.BLACK);

        myCurrentRoomPanel.resetUserController();
        myCurrentRoomPanel.requestFocusInWindow();
        myCurrentRoomPanel.setFocusable(true);

    }

    /**
     * Loads a given room into the room panel. Used for room traversal. Removes
     * all currently displayed elements and property change listeners.
     * Possibly contains redundant code.
     * @param theRoom is the new room to be loaded into the panel.
     * @throws IOException if any resource cannot be loaded.
     */
    public void loadRoom(final Room theRoom) throws IOException {

        myCurrentRoomPanel.userControls.removePropertyChangeListener(myConsolePanel);
        myCurrentRoomPanel.userControls.removePropertyChangeListener(this);
        myCurrentRoomPanel.setFocusable(false);
        myCurrentRoomPanel.setVisible(false);
        this.remove(myCurrentRoomPanel);
        this.remove(myConsolePanel);
        myCurrentRoomPanel = new RoomPanel(myRoomList.get(theRoom.getRoomID()));
        this.add(myCurrentRoomPanel);
        myCurrentRoomPanel.setVisible(true);
        myCurrentRoomPanel.setBounds(-96, 0, 864, 768);
        myCurrentRoomPanel.requestFocusInWindow();
        this.addConsolePanel();
        myCurrentRoomPanel.userControls.getPlayer().reset();
        myCurrentRoomPanel.userControls.addPropertyChangeListener(myConsolePanel);
        myCurrentRoomPanel.userControls.addPropertyChangeListener(this);
        repaint();
    }

    /**
     * Property change listener. Loads a new room into the current room panel
     * if user controller positions a sprite within proximity to a door.
     * @param evt is the received property change.
     */
    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        switch (evt.getPropertyName()) {
            case PROPERTY_PROXIMITY_DOOR_A -> {
                if (myCurrentRoomPanel.myCurrentRoom.getRoomA() != null) {
                    try {loadRoom(myCurrentRoomPanel.myCurrentRoom.getRoomA());}
                    catch (IOException e) {e.printStackTrace();}
                }
            }
            case PROPERTY_PROXIMITY_DOOR_B -> {
                if (myCurrentRoomPanel.myCurrentRoom.getRoomB() != null) {
                    try {loadRoom(myCurrentRoomPanel.myCurrentRoom.getRoomB());}
                    catch (IOException e) {e.printStackTrace();}
                }
            }
            case PROPERTY_PROXIMITY_DOOR_C -> {
                if (myCurrentRoomPanel.myCurrentRoom.getRoomC() != null) {
                    try {loadRoom(myCurrentRoomPanel.myCurrentRoom.getRoomC());}
                    catch (IOException e) {e.printStackTrace();}
                }
            }
            case PROPERTY_PROXIMITY_DOOR_D -> {
                if (myCurrentRoomPanel.myCurrentRoom.getRoomD() != null) {
                    try {loadRoom(myCurrentRoomPanel.myCurrentRoom.getRoomD());}
                    catch (IOException e) {e.printStackTrace();}
                }
            }
        }
    }


    /**
     * Attempts to set look and feel to system defaults. Reverts to
     * default Swing UI if any error encountered.
     *
     * @throws ClassNotFoundException          catches UI setup errors.
     * @throws InstantiationException          catches UI setup errors.
     * @throws IllegalAccessException          catches UI setup errors.
     * @throws UnsupportedLookAndFeelException catches UI setup errors.
     */
    private void setupUI() throws

            ClassNotFoundException,
            InstantiationException,
            IllegalAccessException,
            UnsupportedLookAndFeelException {
        try {
            // Set System L&F
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        } catch (final UnsupportedLookAndFeelException
                | IllegalAccessException
                | InstantiationException
                | ClassNotFoundException e) {
            UIManager.setLookAndFeel(
                    UIManager.getCrossPlatformLookAndFeelClassName());
        }
    }

}
